services:
  - type: web
    name: hotel-api
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run clean && npx tsc
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
